repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ".virtual_documents"
        language_version: python3.8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ".virtual_documents"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v0.790" # Use the sha / tag you want to point at
  #   hooks:
  #     - id: mypy
  #       # args: [--strict, --ignore-missing-imports]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-ast
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m coverage run -m unittest discover
        language: system
        pass_filenames: false
      - id: coverage
        name: coverage
        entry: python -m coverage report -m --fail-under=100
        language: system
        pass_filenames: false
