name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -q --upgrade pip
          pip install -q -r requirements.txt
          pip install -q --upgrade codecov coverage black flake8 codacy-coverage
      - name: Lint
        run: |
          black --check --diff mfs
          flake8 --count mfs
      - name: Tests & coverage
        run: |
          coverage run -m unittest -v mfs.tests
          coverage report -m --fail-under=100
